---
name: ((deployment_name))

releases:
- name: concourse
  version: ((concourse_version))
  sha1: ((concourse_sha1))
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=((concourse_version))
- name: bpm
  version: ((bpm_version))
  sha1: ((bpm_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=((bpm_version))
- name: postgres
  version: ((postgres_version))
  sha1: ((postgres_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=((postgres_version))

instance_groups:
- name: concourse
  instances: 1
  vm_type: ((concourse_vm_type))
  persistent_disk_type: ((concourse_persistent_disk_type))
  stemcell: xenial
  azs: [z1]
  networks:
  - name: ((network_name))
  jobs:
  - release: bpm
    name: bpm
  - release: concourse
    name: web
    properties:
      token_signing_key: ((token_signing_key))

      external_url: ((external_url))

      postgresql:
        host: 127.0.0.1
        database: atc
        sslmode: disable
        role:
          name: atc
          password: ((postgres_password))
      add_local_users:
        concourse: ((concourse_password))
      main_team:
        auth:
          local:
            users:
            - concourse
      worker_gateway:
        host_key: ((tsa_host_key))
        authorized_keys: [((worker_key.public_key))]

  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: atc
        roles:
        - name: atc
          password: ((postgres_password))

  - release: concourse
    name: worker
    properties:
      drain_timeout: 10m

      worker_gateway:
        hosts: ["127.0.0.1:2222"]
        host_public_key: ((tsa_host_key.public_key))
        worker_key: ((worker_key))

      garden:
        allow_host_access: true

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
